### ISSUE TITLE
Λάθος format string για τις ημερομηνίες στο ProtocolController.php

### ISSUE THREAD

**Issue by pc-down** [g-theodoroy/electronic_protocol#12]
Σε διάφορα σημεία στο ProtocolController.php έχει γραφεί κατά λάθος για την μορφοποίηση ημερομηνιών το `format('d/m/Y H:m:s')` ενώ το σωστό είναι `format('d/m/Y H:i:s')`

Επί τη ευκαιρία, που είναι καλύτερο να αναφέρονται τα bugs ή οι προτάσεις, εδώ ή στο forum;

**Comment by g-theodoroy** [comment]
Ευχαριστώ
το διορθώνω
