### ISSUE TITLE
Windows 10 Installation with XAMPP

### ISSUE THREAD

**Issue by sarlisj** [g-theodoroy/electronic_protocol#4]
I tried to install electronic protocol but I faced the following error:

![image](https://user-images.githubusercontent.com/11905651/103586757-6c3c3480-4eee-11eb-89a6-c9ed10dc4e09.png)

can you help?

**Comment by g-theodoroy** [comment]
Maybe the next video may help you

https://www.youtube.com/watch?v=xvDHwjHb7wc
